# Generated by Django 4.2.5 on 2023-10-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='webiste',
            field=models.CharField(max_length=300),
        ),
    ]
