# Generated by Django 4.2.5 on 2023-10-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_customuser_managers_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='ID',
        ),
    ]
