# Generated by Django 4.2.5 on 2023-10-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_rename_id_customuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ID',
            new_name='id',
        ),
    ]
