# Generated by Django 4.2.5 on 2023-10-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_customuser_user_type'),
        ('APIs', '0004_rename_id_customuser_id'),
    ]

    operations = [
    ]
