# Generated by Django 4.2.5 on 2023-09-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_alter_profile_academic_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_Record',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='internship_exp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='research_exp',
            field=models.TextField(),
        ),
    ]
